[package]
name = "Pathie"
version = "0.1.1"
edition = "2021"

[dependencies]
log = "0.4"
chrono = "0.4.22"
ash = "0.37"
env_logger = "0.9.1"
winit = "0.27.4"
cgmath = "0.18.0"
x11 = "2.20.0"
ash-window = "0.12.0"
raw-window-handle = "0.5.0"
strum = "0.24"
strum_macros = "0.24"
rand = "0.8.5"

